# Generated by Django 3.0.2 on 2020-07-20 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('card_no', models.CharField(max_length=16)),
                ('pin', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(max_length=100000)),
                ('Entery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Entery')),
            ],
        ),
    ]
